packages:
  - backend
  - frontend

ignoredBuiltDependencies:
  - '@compodoc/compodoc'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - bcrypt
  - msgpackr-extract
  - sharp
