name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # âš ï¸ à¸•à¹‰à¸­à¸‡à¸•à¸£à¸‡à¸à¸±à¸š Label à¸‚à¸­à¸‡ Runner à¹ƒà¸™ Gitea Settings (à¹€à¸Šà¹ˆà¸™ self-hosted)
    steps:
      - name: Deploy to QNAP via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop_signal: true # Stop script on error
          script: |
            # âš ï¸ QNAP SSH à¹„à¸¡à¹ˆà¸¡à¸µ PATH à¹€à¸•à¹‡à¸¡ à¸•à¹‰à¸­à¸‡ export à¹€à¸­à¸‡
            # docker: /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker
            # git:    /opt/bin/git
            export PATH="/share/CACHEDEV1_DATA/.qpkg/container-station/bin:/opt/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

            echo "ðŸš€ Starting Deployment..."

            # 1. Update Code
            echo "ðŸ“‚ Pulling latest code..."
            cd /share/np-dms/app/source/lcbp3
            git pull origin main

            # 2. Build Backend
            echo "ðŸ—ï¸ Building Backend..."
            docker build -f backend/Dockerfile -t lcbp3-backend:latest .

            # 3. Build Frontend
            echo "ðŸ—ï¸ Building Frontend..."
            docker build -f frontend/Dockerfile \
              --build-arg NEXT_PUBLIC_API_URL=https://backend.np-dms.work/api \
              -t lcbp3-frontend:latest .

            # 4. Update Containers
            echo "ðŸ”„ Updating Containers..."
            cd /share/np-dms/app
            # âš ï¸ à¸•à¹‰à¸­à¸‡ rm -f à¹€à¸žà¸£à¸²à¸° container à¹€à¸”à¸´à¸¡à¸­à¸²à¸ˆà¸ªà¸£à¹‰à¸²à¸‡à¸ˆà¸²à¸ compose à¸„à¸™à¸¥à¸° project
            docker rm -f backend frontend 2>/dev/null || true
            docker compose -f docker-compose-app.yml up -d

            # 5. Cleanup
            echo "ðŸ§¹ Cleaning up unused images..."
            docker image prune -f

            echo "âœ… Deployment Complete!"
